### ISSUE TITLE
Issue: Program does not accept nor ignore non .txt file in the input folder.

### ISSUE THREAD

**Issue by liutng** [P-DR0ZD/pdrozd-ssg#1]
If a non-txt file exhibits in the input folder, the non-txt file will also be processed by the program. Also, if a binary file exhibits in the input folder, the program will give a "No option for --input" error prompt.

**Comment by P-DR0ZD** [comment]
Fixed this issue by checking the file extension of the files. Then I needed to change how my index function would work as it would create an empty index so i made the program end instead of making an index
