### ISSUE TITLE
Improve: Add config file support.

### ISSUE THREAD

**Issue by liutng** [P-DR0ZD/pdrozd-ssg#12]
# Description
Add config file support for input arguments.
# Requirement
* The -c or --config flags accept a file path to a JSON config file.
* If the file is missing, or can't be parsed as JSON, exit with an appropriate error message.
* If the -c or --config option is provided, ignore all other options (i.e., a config file overrides other options on the command line).
* The program should ignore any options in the config file it doesn't recognize. For example, if the SSG doesn't support stylesheets, ignore a stylesheet property.
* If the config file is missing any options, assume the usual defaults. For example, use dist/ as the output directory if it isn't specified.

**Comment by P-DR0ZD** [comment]
Merged the Issue using remote
