### ISSUE TITLE
Issue: Does not support fully qualified path.

### ISSUE THREAD

**Issue by liutng** [P-DR0ZD/pdrozd-ssg#3]
# Issue
 Program prompts "File or directory dosen't exsit (make sure file extension is included)" when fully qualified path(absolute path) is passed as the argument of --input.
# Fix
Add fully qualified path support.

**Comment by P-DR0ZD** [comment]
I fixed this issue by first checking if the passed argument is an absolute path or not if it isn't then I make it an absolute path and then use it
